"""Unified repository — delegates to pg_repo when DATABASE_URL is set, otherwise file_repo."""
from src.app.config import settings

if settings.use_postgres:
    from src.app.storage.pg_repo import (  # noqa: F401
        bootstrap_schema,
        compute_file_hash,
        get_learned_mapping,
        get_project,
        get_proposal,
        get_review_item,
        get_revision,
        get_ruleset,
        get_source_file_path,
        get_validation,
        list_all_validations,
        list_learned_mappings,
        list_learning_events,
        list_projects,
        list_proposals,
        list_review_items,
        list_revisions,
        list_rulesets,
        list_validations_for_project,
        load_facts,
        load_findings,
        log_audit_event,
        report_path,
        save_facts,
        save_findings,
        save_learned_mapping,
        save_learning_event,
        save_project,
        save_proposal,
        save_proposals,
        save_review_item,
        save_revision,
        save_ruleset,
        save_validation,
        store_source_file,
        update_fact,
    )
else:
    from src.app.storage.file_repo import (  # noqa: F401
        compute_file_hash,
        get_learned_mapping,
        get_project,
        get_proposal,
        get_review_item,
        get_revision,
        get_ruleset,
        get_source_file_path,
        get_validation,
        list_all_validations,
        list_learned_mappings,
        list_learning_events,
        list_projects,
        list_proposals,
        list_review_items,
        list_revisions,
        list_rulesets,
        list_validations_for_project,
        load_facts,
        load_findings,
        log_audit_event,
        report_path,
        save_facts,
        save_findings,
        save_learned_mapping,
        save_learning_event,
        save_project,
        save_proposal,
        save_proposals,
        save_review_item,
        save_revision,
        save_ruleset,
        save_validation,
        store_source_file,
        update_fact,
    )

    def bootstrap_schema() -> None:  # noqa: F811
        pass
